# Generated by Django 3.0.4 on 2020-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0002_auto_20200330_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='status',
            field=models.IntegerField(choices=[(1, 'queued'), (2, 'finished'), (3, 'failed'), (4, 'started'), (5, 'deferred'), (6, 'scheduled'), (7, 'unknown')], default=7),
        ),
    ]
