# Generated by Django 3.0.4 on 2020-04-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0008_storagebackend'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='storage_backend',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='omnetppManager.StorageBackend'),
        ),
    ]
