# Generated by Django 3.0.4 on 2020-05-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0009_simulation_storage_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebackend',
            name='backend_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='backend_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='backend_identifier',
            field=models.CharField(default='dropbox', max_length=100),
        ),
        migrations.AddField(
            model_name='storagebackend',
            name='backend_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
