# Generated by Django 3.0.4 on 2020-05-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0012_auto_20200507_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigKeyValueStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True)),
                ('config_value', models.CharField(max_length=100)),
            ],
        ),
    ]
