# Generated by Django 3.0.4 on 2020-05-25 13:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0013_configkeyvaluestorage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='configkeyvaluestorage',
            managers=[
                ('config', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='configkeyvaluestorage',
            name='config_type',
            field=models.IntegerField(choices=[(1, 'integer'), (2, 'boolean'), (3, 'text')], default=3),
        ),
    ]
