# Generated by Django 3.0.4 on 2020-05-25 13:47

from django.db import migrations, models
import omnetppManager.models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0016_remove_configkeyvaluestorage_config_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configkeyvaluestorage',
            name='config_value',
            field=models.CharField(help_text='A python expression like "abc", [1, 2, 3], True etc.', max_length=100, validators=[omnetppManager.models.is_valid_python]),
        ),
    ]
