# Generated by Django 3.0.4 on 2020-07-10 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0020_simomnetpptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='simulation_enqueue_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulation_timeout',
            field=models.IntegerField(default=0),
        ),
    ]
