# Generated by Django 3.0.4 on 2020-07-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0024_remove_mobilitymodelparameter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilitymodel',
            name='omnetppini_config_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
