# Generated by Django 3.0.4 on 2020-07-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0026_mobilitymodelparameter_user_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='OmnetppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OmnetppConfigParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100)),
                ('param_default_value', models.CharField(max_length=100)),
                ('user_editable', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='omnetppManager.OmnetppConfig')),
            ],
        ),
        migrations.CreateModel(
            name='OmnetppConfigType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mobilitymodelparameter',
            name='mobility_model',
        ),
        migrations.DeleteModel(
            name='MobilityModel',
        ),
        migrations.DeleteModel(
            name='MobilityModelParameter',
        ),
        migrations.AddField(
            model_name='omnetppconfig',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_type', to='omnetppManager.OmnetppConfigType'),
        ),
    ]
