# Generated by Django 3.0.4 on 2020-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0030_omnetppconfigparameter_param_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omnetppconfigparameter',
            name='param_description',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='omnetppconfigparameter',
            name='param_unit',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
