# Generated by Django 3.0.4 on 2020-11-30 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0039_serverconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfigValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key for the value', max_length=30)),
                ('value', models.CharField(help_text='The value for the key', max_length=30)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnetppManager.ServerConfig')),
            ],
        ),
    ]
