# Generated by Django 3.0.4 on 2021-06-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0043_simulation_simulation_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='simulation_state_times',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
