# Generated by Django 3.0.4 on 2021-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0045_simulation_simulation_is_debug_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='terminated',
            field=models.IntegerField(choices=[(1, 'Simulation not terminated'), (2, 'Terminated by user'), (3, 'Terminated by system: Exceeded events.'), (4, 'Terminated by system: Exceeded CPU.'), (5, 'Terminated by system: Exceeded RAM.'), (6, 'Terminated by system: Exceeded Disk space.')], default=1),
        ),
    ]
