# Generated by Django 3.2 on 2021-08-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0051_auto_20210816_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnetppbenchmarkforwarderparameters',
            name='param_display_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
