# Generated by Django 3.0 on 2021-10-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0052_omnetppbenchmarkforwarderparameters_param_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnetppbenchmarkforwarderparameters',
            name='param_type',
            field=models.IntegerField(choices=[(1, 'fixed'), (2, 'range')], default=1),
        ),
    ]
