# Generated by Django 3.0 on 2021-10-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0054_auto_20211011_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='omnetppbenchmarkforwarderparameters',
            name='param_user_option',
            field=models.CharField(default='', help_text='users allowed options entered as a list', max_length=100),
        ),
    ]
