# Generated by Django 3.2.13 on 2022-05-09 11:12

from django.db import migrations
import omnetppManager.fields


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0057_auto_20220429_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagebackend',
            name='backend_config',
            field=omnetppManager.fields.JSONField(default='', null=True),
        ),
    ]
