# Generated by Django 3.0 on 2021-12-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0057_userprofile_userprofileparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='server',
        ),
    ]
