# Generated by Django 3.0 on 2021-12-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0058_remove_userprofile_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='sim_server',
            field=models.CharField(default='', max_length=250),
        ),
    ]
