# Generated by Django 3.2.13 on 2022-05-09 11:13

from django.db import migrations
import omnetppManager.fields


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0058_storagebackend_backend_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebackend',
            name='backend_config',
            field=omnetppManager.fields.JSONField(blank=True, default='', null=True),
        ),
    ]
