# Generated by Django 3.2.13 on 2022-05-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnetppManager', '0060_alter_storagebackend_backend_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagebackend',
            name='backend_config',
            field=models.JSONField(blank=True, default=str, null=True),
        ),
    ]
